"""UI-agnostic application layer (roadmap 8.1 to 8.3; planning §4.7).

View models, user-facing copy (including the §1 disclaimer), display
formatting, form parsing, session state, and first-run state for any
UI shell. Everything here is plain typed Python over the scenario
layer and engine — no Qt imports (guard test), no assumption of a
desktop — so a future web shell can reuse it unchanged.
"""

from glidepath.app.charts import (
    DEFAULT_CHART_BASIS,
    NO_PROJECTION_MESSAGE,
    RUN_FAILED_PREFIX,
    ChartBasisOption,
    ChartSeries,
    ChartSpec,
    ChartsViewModel,
    bar_tooltip,
    basis_from_key,
    build_charts_view_model,
)
from glidepath.app.copy import (
    ABOUT_TITLE,
    APP_NAME,
    DATE_PICKER_TOOLTIP,
    DISCLAIMER_ACCEPT_LABEL,
    DISCLAIMER_BODY,
    DISCLAIMER_DECLINE_LABEL,
    DISCLAIMER_TITLE,
    HELP_GUIDE_INTRO,
    HELP_GUIDE_SECTIONS,
    HELP_GUIDE_TITLE,
    HELP_MENU_LABEL,
)
from glidepath.app.display import (
    format_date,
    format_money,
    format_recorded,
    format_value,
)
from glidepath.app.example import example_facts_form_data
from glidepath.app.files import (
    NOTHING_TO_SAVE_MESSAGE,
    LoadOutcome,
    SaveOutcome,
    document_from_state,
    load_plan_state,
    save_plan_state,
)
from glidepath.app.firstrun import (
    FirstRunState,
    default_state_path,
    load_state,
    record_disclaimer_acknowledged,
    record_last_plan_path,
)
from glidepath.app.forms import (
    ChoiceOption,
    FactsFormData,
    FactsFormResult,
    FactsFormViewModel,
    FieldKind,
    FieldSpec,
    FormError,
    SectionSpec,
    build_facts_form_view_model,
    facts_form_data_from_household,
    form_cannot_represent,
    format_form_errors,
    parse_facts_form,
)
from glidepath.app.inspector import (
    AssumptionRow,
    DecisionRow,
    FactRow,
    InspectorViewModel,
    RollForwardRow,
    StructureRow,
    build_inspector_view_model,
)
from glidepath.app.plan import (
    OVERRIDE_SOURCE,
    OverrideOutcome,
    PlanState,
    facts_saved_message,
    initial_plan_state,
    state_with_household,
    state_with_override,
    state_with_scenarios,
)
from glidepath.app.scenarios import (
    DEFAULT_COMPARISON_METRIC_KEY,
    ComparisonMetricOption,
    OverrideRow,
    ScenarioItem,
    ScenariosViewModel,
    TargetOption,
    build_scenarios_view_model,
    metric_from_key,
    scenario_target_options,
    state_with_scenario_added,
    state_with_scenario_override,
    state_without_scenario,
    state_without_scenario_override,
)
from glidepath.app.shell import (
    AboutViewModel,
    DisclaimerViewModel,
    FileMenuViewModel,
    HelpGuideViewModel,
    HelpSectionViewModel,
    ShellViewModel,
    build_shell_view_model,
    should_show_disclaimer,
)
from glidepath.core import ReportBasis

__all__ = [
    "ABOUT_TITLE",
    "APP_NAME",
    "DATE_PICKER_TOOLTIP",
    "DEFAULT_CHART_BASIS",
    "DEFAULT_COMPARISON_METRIC_KEY",
    "DISCLAIMER_ACCEPT_LABEL",
    "DISCLAIMER_BODY",
    "DISCLAIMER_DECLINE_LABEL",
    "DISCLAIMER_TITLE",
    "HELP_GUIDE_INTRO",
    "HELP_GUIDE_SECTIONS",
    "HELP_GUIDE_TITLE",
    "HELP_MENU_LABEL",
    "NOTHING_TO_SAVE_MESSAGE",
    "NO_PROJECTION_MESSAGE",
    "OVERRIDE_SOURCE",
    "RUN_FAILED_PREFIX",
    "AboutViewModel",
    "AssumptionRow",
    "ChartBasisOption",
    "ChartSeries",
    "ChartSpec",
    "ChartsViewModel",
    "ChoiceOption",
    "ComparisonMetricOption",
    "DecisionRow",
    "DisclaimerViewModel",
    "FactRow",
    "FactsFormData",
    "FactsFormResult",
    "FactsFormViewModel",
    "FieldKind",
    "FieldSpec",
    "FileMenuViewModel",
    "FirstRunState",
    "FormError",
    "HelpGuideViewModel",
    "HelpSectionViewModel",
    "InspectorViewModel",
    "LoadOutcome",
    "OverrideOutcome",
    "OverrideRow",
    "PlanState",
    "ReportBasis",
    "RollForwardRow",
    "SaveOutcome",
    "ScenarioItem",
    "ScenariosViewModel",
    "SectionSpec",
    "ShellViewModel",
    "StructureRow",
    "TargetOption",
    "bar_tooltip",
    "basis_from_key",
    "build_charts_view_model",
    "build_facts_form_view_model",
    "build_inspector_view_model",
    "build_scenarios_view_model",
    "build_shell_view_model",
    "default_state_path",
    "document_from_state",
    "example_facts_form_data",
    "facts_form_data_from_household",
    "facts_saved_message",
    "form_cannot_represent",
    "format_date",
    "format_form_errors",
    "format_money",
    "format_recorded",
    "format_value",
    "initial_plan_state",
    "load_plan_state",
    "load_state",
    "metric_from_key",
    "parse_facts_form",
    "record_disclaimer_acknowledged",
    "record_last_plan_path",
    "save_plan_state",
    "scenario_target_options",
    "should_show_disclaimer",
    "state_with_household",
    "state_with_override",
    "state_with_scenario_added",
    "state_with_scenario_override",
    "state_with_scenarios",
    "state_without_scenario",
    "state_without_scenario_override",
]
