"""UK region package (planning §4.2, §5.3).

Implements the core boundary protocols for the UK. Every UK policy
figure — tax bands, allowances, state pension rates, age rules — is
loaded from the TOML data files under ``data/`` (each carrying
``verified_on`` + ``sources``), never hardcoded; a guard test enforces
this. Shipped default assumptions mirror planning §7 and are kept in
sync by a doc-sync test.
"""

from glidepath.regions.uk.ages import UkAgeError, UkAgeRules
from glidepath.regions.uk.contributions import (
    AnnualAllowanceAssessment,
    CarryForwardOutcome,
    UkContributionError,
    UkContributionRuleset,
    adjusted_income,
    apply_carry_forward,
    assess_annual_allowance,
    carry_forward_generated,
    db_pension_input_amount,
    is_mpaa_active,
    roll_carry_forward,
    tapered_annual_allowance,
    threshold_income,
)
from glidepath.regions.uk.extension import (
    FutureYearsExtension,
    FutureYearsMode,
    FutureYearsPolicy,
    ScottishBandsPolicy,
    extend_tax_year,
)
from glidepath.regions.uk.loader import (
    AGE_RULES_FILENAME,
    ASSUMPTIONS_FILENAME,
    RETURNS_HISTORY_FILENAME,
    available_tax_years,
    data_file_digest,
    load_age_rules,
    load_default_assumptions,
    load_returns_history,
    load_tax_year,
    parse_age_rules,
    parse_default_assumptions,
    parse_returns_history,
    parse_tax_year,
    tax_year_filename,
)
from glidepath.regions.uk.region import (
    default_assumption_set,
    future_years_extension,
    uk_region,
)
from glidepath.regions.uk.schema import (
    SCHEMA_VERSION,
    AgeRulesFile,
    AssumptionDefault,
    AssumptionsFile,
    AssumptionValue,
    DataFileError,
    DeathBenefitAges,
    DividendRate,
    DividendRules,
    FileMeta,
    IncomeTaxSchedule,
    IsaRules,
    LisaAges,
    MarriageAllowanceRules,
    NmpaStep,
    PensionRules,
    ReturnsHistoryFile,
    SavingsRate,
    SavingsRules,
    SpaAgeBand,
    SpaBand,
    SpaDateBand,
    StatePensionDeferral,
    TaxBand,
    TaxYearFile,
    TaxYearMeta,
)
from glidepath.regions.uk.state_pension import (
    UkStatePensionError,
    UkStatePensionScheme,
)
from glidepath.regions.uk.tax import (
    DIVIDEND_NIL_RATE_BAND,
    MARRIAGE_ALLOWANCE_BAND,
    RUK_RESIDENCY,
    SAVINGS_NIL_RATE_BAND,
    SAVINGS_STARTING_RATE_BAND,
    SCOTLAND_RESIDENCY,
    UkTaxError,
    UkTaxSystem,
)
from glidepath.regions.uk.wrappers import (
    CASH_KIND,
    GIA_KIND,
    ISA_ALLOWANCE_GROUP,
    ISA_KIND,
    LISA_ALLOWANCE_GROUP,
    LISA_KIND,
    SIPP_KIND,
    WORKPLACE_DC_KIND,
    UkWrapperError,
    UkWrapperRuleset,
)
from glidepath.regions.uk.years import TaxYearSeries, UkTaxYearError

__all__ = [
    "AGE_RULES_FILENAME",
    "ASSUMPTIONS_FILENAME",
    "CASH_KIND",
    "DIVIDEND_NIL_RATE_BAND",
    "GIA_KIND",
    "ISA_ALLOWANCE_GROUP",
    "ISA_KIND",
    "LISA_ALLOWANCE_GROUP",
    "LISA_KIND",
    "MARRIAGE_ALLOWANCE_BAND",
    "RETURNS_HISTORY_FILENAME",
    "RUK_RESIDENCY",
    "SAVINGS_NIL_RATE_BAND",
    "SAVINGS_STARTING_RATE_BAND",
    "SCHEMA_VERSION",
    "SCOTLAND_RESIDENCY",
    "SIPP_KIND",
    "WORKPLACE_DC_KIND",
    "AgeRulesFile",
    "AnnualAllowanceAssessment",
    "AssumptionDefault",
    "AssumptionValue",
    "AssumptionsFile",
    "CarryForwardOutcome",
    "DataFileError",
    "DeathBenefitAges",
    "DividendRate",
    "DividendRules",
    "FileMeta",
    "FutureYearsExtension",
    "FutureYearsMode",
    "FutureYearsPolicy",
    "IncomeTaxSchedule",
    "IsaRules",
    "LisaAges",
    "MarriageAllowanceRules",
    "NmpaStep",
    "PensionRules",
    "ReturnsHistoryFile",
    "SavingsRate",
    "SavingsRules",
    "ScottishBandsPolicy",
    "SpaAgeBand",
    "SpaBand",
    "SpaDateBand",
    "StatePensionDeferral",
    "TaxBand",
    "TaxYearFile",
    "TaxYearMeta",
    "TaxYearSeries",
    "UkAgeError",
    "UkAgeRules",
    "UkContributionError",
    "UkContributionRuleset",
    "UkStatePensionError",
    "UkStatePensionScheme",
    "UkTaxError",
    "UkTaxSystem",
    "UkTaxYearError",
    "UkWrapperError",
    "UkWrapperRuleset",
    "adjusted_income",
    "apply_carry_forward",
    "assess_annual_allowance",
    "available_tax_years",
    "carry_forward_generated",
    "data_file_digest",
    "db_pension_input_amount",
    "default_assumption_set",
    "extend_tax_year",
    "future_years_extension",
    "is_mpaa_active",
    "load_age_rules",
    "load_default_assumptions",
    "load_returns_history",
    "load_tax_year",
    "parse_age_rules",
    "parse_default_assumptions",
    "parse_returns_history",
    "parse_tax_year",
    "roll_carry_forward",
    "tapered_annual_allowance",
    "tax_year_filename",
    "threshold_income",
    "uk_region",
]
