"""Region-agnostic core primitives (roadmap Phase 1).

The core defines value types, calendars, provenance kinds and entities.
It never imports region code (planning §4.2) — enforced by a guard test —
and never contains policy figures, which live in region data files.
"""

from glidepath.core.config import EngineError, RunConfig, RunMode
from glidepath.core.contributions import (
    ContributionRuleset,
    ContributionSchedule,
    MemberContributionOutcome,
    MemberContributionRequest,
)
from glidepath.core.engine import run
from glidepath.core.entities import (
    EntityId,
    Household,
    Person,
    PlannedOutflow,
    Sex,
    SpendingPlan,
    TaxResidencyId,
    new_entity_id,
    validate_household_v1,
)
from glidepath.core.glide import (
    GlidePathConfig,
    GlidePathPoint,
    LifeStage,
    glide_path_from_shape,
    years_to_target_retirement,
)
from glidepath.core.investments import (
    AssetAllocation,
    AssetReturns,
    FeesAndGrowthOutcome,
    FeeSchedule,
    apply_fees_and_growth,
    period_fee,
)
from glidepath.core.money import Money, Rate
from glidepath.core.pensions import (
    DBPension,
    FactorTable,
    RevaluationBasis,
    RevaluationReference,
    db_early_late_factor,
    db_start_date,
    db_taken_age,
    revaluation_factor_for_months,
)
from glidepath.core.periods import (
    AgeRules,
    AnnualCalendar,
    FiscalCalendar,
    Period,
    add_months,
    age_on,
    birthday_in_year,
    date_age_attained,
    entitlement_active_fraction,
    is_age_attained_by_period_start,
    period_active_fraction,
    prorata_fraction,
    whole_months_between,
)
from glidepath.core.provenance import (
    Assumption,
    AssumptionKey,
    AssumptionReadRecorder,
    AssumptionSet,
    Decision,
    Fact,
    Provenance,
    TrackedAssumptions,
    decimal_assumption_value,
    int_assumption_value,
    mapping_assumption_value,
)
from glidepath.core.region import Region
from glidepath.core.reporting import (
    PeriodReportRow,
    ProjectionReport,
    ReportBasis,
    WrapperReportBalance,
    build_report,
)
from glidepath.core.results import (
    LabelledDecision,
    LabelledFact,
    PeriodSnapshot,
    PersonPeriodResult,
    ProjectionResult,
    RunProvenance,
    WrapperPeriodResult,
    collect_plan_decisions,
    collect_plan_facts,
)
from glidepath.core.returns import (
    DeterministicReturnModel,
    PeriodReturns,
    ReturnModel,
    nominal_rate,
)
from glidepath.core.state_pension import (
    StatePensionEntitlement,
    StatePensionRecord,
    StatePensionScheme,
    StatePensionUprating,
    UpratingRule,
    deferral_months,
)
from glidepath.core.tax import TaxInput, TaxLine, TaxResult, TaxSystem
from glidepath.core.withdrawals import (
    FixedPercentWithdrawalStrategy,
    FixedRealWithdrawalStrategy,
    GrossDraw,
    GrossWithdrawalPlan,
    NetWithdrawalPlan,
    TaxFreeCashStrategy,
    WithdrawalPlan,
    WithdrawalSource,
    WithdrawalSourceId,
    WithdrawalState,
    WithdrawalStrategy,
    tax_aware_order,
)
from glidepath.core.wrappers import (
    ContributionTaxTreatment,
    GrowthTaxTreatment,
    ReliefMechanic,
    WithdrawalTaxTreatment,
    Wrapper,
    WrapperKindId,
    WrapperRuleset,
    WrapperTaxTreatment,
)

__all__ = [
    "AgeRules",
    "AnnualCalendar",
    "AssetAllocation",
    "AssetReturns",
    "Assumption",
    "AssumptionKey",
    "AssumptionReadRecorder",
    "AssumptionSet",
    "ContributionRuleset",
    "ContributionSchedule",
    "ContributionTaxTreatment",
    "DBPension",
    "Decision",
    "DeterministicReturnModel",
    "EngineError",
    "EntityId",
    "Fact",
    "FactorTable",
    "FeeSchedule",
    "FeesAndGrowthOutcome",
    "FiscalCalendar",
    "FixedPercentWithdrawalStrategy",
    "FixedRealWithdrawalStrategy",
    "GlidePathConfig",
    "GlidePathPoint",
    "GrossDraw",
    "GrossWithdrawalPlan",
    "GrowthTaxTreatment",
    "Household",
    "LabelledDecision",
    "LabelledFact",
    "LifeStage",
    "MemberContributionOutcome",
    "MemberContributionRequest",
    "Money",
    "NetWithdrawalPlan",
    "Period",
    "PeriodReportRow",
    "PeriodReturns",
    "PeriodSnapshot",
    "Person",
    "PersonPeriodResult",
    "PlannedOutflow",
    "ProjectionReport",
    "ProjectionResult",
    "Provenance",
    "Rate",
    "Region",
    "ReliefMechanic",
    "ReportBasis",
    "ReturnModel",
    "RevaluationBasis",
    "RevaluationReference",
    "RunConfig",
    "RunMode",
    "RunProvenance",
    "Sex",
    "SpendingPlan",
    "StatePensionEntitlement",
    "StatePensionRecord",
    "StatePensionScheme",
    "StatePensionUprating",
    "TaxFreeCashStrategy",
    "TaxInput",
    "TaxLine",
    "TaxResidencyId",
    "TaxResult",
    "TaxSystem",
    "TrackedAssumptions",
    "UpratingRule",
    "WithdrawalPlan",
    "WithdrawalSource",
    "WithdrawalSourceId",
    "WithdrawalState",
    "WithdrawalStrategy",
    "WithdrawalTaxTreatment",
    "Wrapper",
    "WrapperKindId",
    "WrapperPeriodResult",
    "WrapperReportBalance",
    "WrapperRuleset",
    "WrapperTaxTreatment",
    "add_months",
    "age_on",
    "apply_fees_and_growth",
    "birthday_in_year",
    "build_report",
    "collect_plan_decisions",
    "collect_plan_facts",
    "date_age_attained",
    "db_early_late_factor",
    "db_start_date",
    "db_taken_age",
    "decimal_assumption_value",
    "deferral_months",
    "entitlement_active_fraction",
    "glide_path_from_shape",
    "int_assumption_value",
    "is_age_attained_by_period_start",
    "mapping_assumption_value",
    "new_entity_id",
    "nominal_rate",
    "period_active_fraction",
    "period_fee",
    "prorata_fraction",
    "revaluation_factor_for_months",
    "run",
    "tax_aware_order",
    "validate_household_v1",
    "whole_months_between",
    "years_to_target_retirement",
]
